### ISSUE TITLE
Runtime:1.0.2找不到

### ISSUE THREAD

**Issue by luqinx** [sensorsdata/sa-sdk-android-runtime#1]
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.sensorsdata.analytics.android:SensorsAnalyticsSDK-Runtime:1.0.2.
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by wangzhzh** [comment]
//添加 Sensors Analytics maven 库地址
maven {
       url 'https://dl.bintray.com/zouyuhan/maven'
}

这个加了吗？
请参考我们集成文档的第一步：
https://www.sensorsdata.cn/manual/android_sdk.html

**Comment by luqinx** [comment]
👌
